var LIVE_CONFIG = {
    "indexRedirectUrl": "https://intrinsicvalueequity.in/invest_biz/vsl.html",
    "vslCheckoutUrl": "https://premium.intrinsicvalueequity.in/checkout/28180dfc-84a9-488e-854e-9f7958a1b8d7",
    "tyWhatsAppUrl": "https://chat.whatsapp.com/EZzUNyMTkklAxMMQNZw6so",
    "indexTopBarText": "For Indian Business Owners and Promoters with Corporate Surplus of Rs. 5 Crore or More",
    "indexEyebrow": "Free 15-Minute Framework Session",
    "indexHeroTitle": "Here's How Institutions Think About Idle Business <span class=\"hl\">Surplus</span> & Why Most Business Owners Never Have",
    "indexHeroSubtitle": "Nikhil Gangil, SEBI-registered Research Analyst (INH000009047) and IIT Madras alumnus, walks you through a structured, rule-based treasury framework built exclusively for Indian businesses with corporate surplus.",
    "indexHeroChip": "Live Online Session | 15 Min",
    "indexTrustPill1": "Featured in ET Markets",
    "indexTrustPill2": "IIT Madras",
    "indexTrustPill3": "Josh Talks Speaker",
    "indexTrustPill4": "11+ years in market research",
    "indexCtaBtnText": "Watch the Free Session Now",
    "indexRatingText": "SEBI Registered Research Analyst · 11+ years in market research",
    "indexUnderstandTitle": "What you will understand in this session",
    "indexCard1Text": "How institutions think about idle surplus & how most businesses don't",
    "indexCard2Text": "Why liquidity, control, and allocation are the three questions every treasury decision needs to answer",
    "indexCard3Text": "How a rule-based ETF framework works inside your own corporate Demat",
    "indexCard4Text": "Why this is different from mutual funds, PMS, and debt instruments",
    "indexCard5Text": "What the next step looks like if you want to explore further",
    "indexWhoTitle": "Who this framework session is for",
    "indexForYouTitle": "This IS For You If:",
    "indexForYouItem1": "Business turnover Rs. 10 Crore or more",
    "indexForYouItem2": "Corporate surplus of Rs. 5 Crore or more not needed for 6 to 24 months",
    "indexForYouItem3": "Currently dissatisfied with FDs failing to beat the nifty and want to up your Game.",
    "indexForYouItem4": "Currently parking surplus in FD, liquid funds, or current account",
    "indexForYouItem5": "You make the capital allocation decisions in your business",
    "indexNotForYouTitle": "This IS NOT For You If:",
    "indexNotForYouItem1": "You are an individual investor, retail trader, or salaried employee",
    "indexNotForYouItem2": "No corporate structure or corporate Demat",
    "indexNotForYouItem3": "Capital below Rs. 5 Crore",
    "indexNotForYouItem4": "Capital needed within 3 to 4 months",
    "indexSpeakerName": "Nikhil Gangil",
    "indexSpeakerRole": "SEBI-Registered Research Analyst (Registration No. INH000009047)",
    "indexModalTitle": "Watch the 15-Minute Framework Session",
    "indexModalSub": "Enter your details below to access the session immediately",
    "vslHeading": "Watch How Our Advisory Framework Helps You Pick Multibaggers",
    "vslCtaText": "Apply For Strategy Call",
    "tyHeading": "Congratulations! Your Session Request Is Received",
    "tySubheading": "Join our exclusive WhatsApp community for immediate updates and live session links",
    "tyBtnText": "Join WhatsApp Group"
};
